input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
    target => "cowrie"
  }

  if [cowrie][src_ip] {
    geoip {
      source => "[cowrie][src_ip]"
      target => "[cowrie][geoip]"
      database => "/usr/share/GeoIP/GeoLite2-City.mmdb"
    }
  }

  if [cowrie][timestamp] {
    date {
      match => ["[cowrie][timestamp]", "ISO8601", "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'"]
      target => "@timestamp"
    }
  }

  mutate {
    remove_field => ["message", "agent", "ecs", "input", "host"]
  }
}

output {
  elasticsearch {
    hosts => ["http://10.10.10.20:9200"]
    index => "cowrie-logs-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "${ES_PASSWORD}"
  }
}
